### ISSUE TITLE
adding VictoriaMetrics in monitoring section

### ISSUE THREAD

**Issue by sanchiitvijay** [TzuriLabs/awesome-cloud-computing#1]
VictoriaMetrics is a fast, cost-saving, and scalable solution for monitoring and managing time series data. It delivers high performance and reliability, making it an ideal choice for businesses of all sizes.
It is a alternative of promethus and a open source by nokia.

**Comment by danielcristho** [comment]
Hi, thanks for the info! If you're interested, you're welcome to fork, make changes, and open a pull request.

**Comment by sanchiitvijay** [comment]
I have made a pr regarding this issue. Please check it and lmk if there is any issue. :)

**Comment by danielcristho** [comment]
Hi, I just merge your changes. Thanks
